# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNMiChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNMiChat
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'RCTLinkingIOS',
    ]

  target 'RNMiChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNMiChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNMiChat-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNMiChat-tvOS

  target 'RNMiChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
